version: "2.17.2"

services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    networks:
      - network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  backend:
    build: ./backend
    volumes:
      - avatar:/app/avatar
    ports:
      - 3000:3000
    networks:
      - network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  database:
    image: postgres:14.5
    env_file:
      - ./postgres.env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network

  db_admin:
    image: dpage/pgadmin4
    env_file:
      - ./db_admin/.env
    volumes:
      - ./db_admin/servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    networks:
      - network

volumes:
  data:
  avatar:

networks:
  network: