version: "2.17.2"

services:
  frontend:
    build: ./frontend
    ports:
      - 80:5173
    networks:
      - network

  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - network

  database:
    image: postgres:14.5
    env_file:
      - ./postgres.env
    ports:
      - 5432:5432
    networks:
      - network

  db_admin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin4.env
    ports:
      - 5050:80
    networks:
      - network

volumes:
  data:

networks:
  network: